#  PAYME POST METHODS

CARD_CREATE = 'cards.create'
CARD_GET_VERIFY_CODE = 'cards.get_verify_code'
CARD_VERIFY = 'cards.verify'
CARD_REMOVE = 'cards.verify'
CARD_CHECK = 'cards.check'
RECEIPTS_CREATE = 'receipts.create'
RECEIPTS_PAY = 'receipts.pay'
RECEIPTS_SEND = 'receipts.send'
RECEIPTS_CANCEL = 'receipts.cancel'
RECEIPTS_CHECK = 'receipts.check'
RECEIPTS_GET = 'receipts.get'
RECEIPTS_GET_ALL = 'receipts.get_all'
RECEIPTS_SET_FISCAL_DATA = 'receipts.set_fiscal_data'